# Generated by Django 5.1 on 2024-08-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='YOUR TASKS', max_length=128),
        ),
    ]
